# Generated by Django 4.1 on 2022-08-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('messages', models.JSONField(default={'state': 0})),
            ],
        ),
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=256)),
                ('user_id', models.BigIntegerField()),
                ('slug', models.SlugField(max_length=128, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('summ', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=56, null=True)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('location', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brendi', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('logo', models.ImageField(max_length=512, upload_to='')),
                ('img', models.ImageField(max_length=512, upload_to='')),
                ('manitor', models.CharField(max_length=128)),
                ('cpu', models.CharField(max_length=128)),
                ('gpu', models.CharField(max_length=128)),
                ('ram', models.CharField(max_length=128)),
                ('hard', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('ctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tg_Nout_uz.category')),
            ],
        ),
    ]
