# Generated by Django 4.1 on 2022-08-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Praduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brendi', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('logo', models.ImageField(max_length=512, upload_to='')),
                ('img', models.ImageField(upload_to='')),
                ('manitor', models.CharField(max_length=128)),
                ('cpu', models.CharField(max_length=128)),
                ('gpu', models.CharField(max_length=128)),
                ('ram', models.CharField(max_length=128)),
                ('hard', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('brds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tg_Nout_uz.brands')),
                ('ctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tg_Nout_uz.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
