# Generated by Django 4.1 on 2022-08-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0003_remove_tguser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
