# Generated by Django 4.1 on 2022-08-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0005_remove_tguser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='last_name',
        ),
    ]
