# Generated by Django 4.1 on 2022-08-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0006_remove_tguser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
