# Generated by Django 4.1 on 2022-08-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0007_tguser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='last_name',
        ),
    ]
