# Generated by Django 4.1 on 2022-08-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0008_remove_tguser_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Praduct',
            new_name='Product',
        ),
        migrations.AddField(
            model_name='tguser',
            name='last_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
