# Generated by Django 4.1 on 2022-08-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0010_alter_product_brendi_alter_product_cpu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brendi',
        ),
    ]
