# Generated by Django 4.1 on 2022-08-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0012_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='last_name',
        ),
    ]
