# Generated by Django 4.0.6 on 2022-08-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0017_tguser_til'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
