# Generated by Django 4.0.6 on 2022-08-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tg_Nout_uz', '0019_tguser_last_name_alter_tguser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='tguser',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
